package:
  name: melange
  version: "0.23.7"
  epoch: 0
  description: build APKs from source code
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bubblewrap
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

vars:
  microvm-kernel-version: 6.12.23
  microvm-kernel-epoch: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7ec88c684fc5bb5d88b8d6da64bc3e28f6fa670f
      repository: https://github.com/chainguard-dev/melange
      tag: v${{package.version}}

  - runs: |
      make melange
      install -m755 -D ./melange "${{targets.contextdir}}"/usr/bin/melange

  - uses: strip

subpackages:
  - name: melange-microvm-init
    description: Minimal busybox init for microvm workloads
    dependencies:
      runtime:
        - kmod
        - mount
        - iproute2
        - openssh-server
        - util-linux-misc
        - e2fsprogs
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/
          cp init ${{targets.subpkgdir}}/
          mkdir -p -m 0755 \
              ${{targets.subpkgdir}}/etc \
              ${{targets.subpkgdir}}/dev \
              ${{targets.subpkgdir}}/home \
              ${{targets.subpkgdir}}/home/build/ \
              ${{targets.subpkgdir}}/mnt \
              ${{targets.subpkgdir}}/proc \
              ${{targets.subpkgdir}}/root \
              ${{targets.subpkgdir}}/run \
              ${{targets.subpkgdir}}/sys \
              ${{targets.subpkgdir}}/var \
              ${{targets.subpkgdir}}/var/empty
          mkdir -p -m 0777 \
             ${{targets.subpkgdir}}/opt \
             ${{targets.subpkgdir}}/tmp \
             ${{targets.subpkgdir}}/var/cache \
             ${{targets.subpkgdir}}/var/run
          ln -sf /usr/share/zoneinfo/UTC  ${{targets.subpkgdir}}/etc/localtime

  - name: melange-microvm-kernel
    description: Minimal Alpine kernel for microvm workloads
    dependencies:
      runtime:
        - curl
    pipeline:
      - if: ${{build.arch}} == "aarch64"
        uses: fetch
        with:
          expected-sha256: 30891e4a37967187f48da323d81cbe7c06bb9f600ec0c666f2df48feb50813ba
          uri: https://dl-cdn.alpinelinux.org/alpine/edge/main/${{build.arch}}/linux-virt-${{vars.microvm-kernel-version}}-r${{vars.microvm-kernel-epoch}}.apk
      - if: ${{build.arch}} == "x86_64"
        uses: fetch
        with:
          expected-sha256: bcfa2eedd1d18c74abcf8c0315adb470b4ca972b0879d047c64eccf7fd0e1b93
          uri: https://dl-cdn.alpinelinux.org/alpine/edge/main/${{build.arch}}/linux-virt-${{vars.microvm-kernel-version}}-r${{vars.microvm-kernel-epoch}}.apk
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/kernel
          tar -xf ./linux-virt-${{vars.microvm-kernel-version}}-r${{vars.microvm-kernel-epoch}}.apk -C  ${{targets.contextdir}}/var/kernel/ 2>/dev/null
    test:
      environment:
        contents:
          packages:
            - busybox
            - coreutils
      pipeline:
        - runs: |
            set -x
            ls -hal /var/kernel/lib/modules
            ls -hal /var/kernel/boot/vmlinuz-virt

update:
  enabled: true
  github:
    identifier: chainguard-dev/melange
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        apk del wolfi-base busybox
        melange version

        # busybox is needed for the build, but we want to demonstrate
        # that it's not needed at runtime.
        # TODO(jason): Can't currently test this due to container inception nonsense that's just too crazy to justify.
        # melange build example.yaml --arch=x86_64
        melange --help
